### PR TITLE
suggest complete-common-words to optimize dictionary completion

### PR DESCRIPTION
**Pull request by Konfekt**
Let me know what you think; perhaps it is a niche issue that I have as I principally write prose instead of code with Vim. Thank you for your great plug-in, it is every day of tremendous help .

### CODE REVIEW

**Comment by lifepillar** [comment]
No problem merging this, but I'd prefer that the paragraph is added after the current text, not in between.

**Comment by lifepillar** [comment]
Thanks!

**Comment by lifepillar** [comment]
Forgot to mention: I am using Vim a lot for non-coding editing. If you feel like, it would be nice to have a page in MUcomplete's wiki describing how to set up Vim with MUcomplete to work with prose.

**Comment by Konfekt** [comment]
Thanks for the encouragement. I added an [entry](https://github.com/lifepillar/vim-mucomplete/wiki/Suggested-Setup-for-Prose) to the wiki by looking at my own setup Feel free to revise and expand.

**Pull request merged**
