### PR TITLE
Implement custom dict method

### PR DESCRIPTION
**Pull request by lacygoill**
Hello,

this is an attempt at implementing a custom `dict `method to get around the issue discussed [here](https://github.com/lifepillar/vim-mucomplete/issues/43).

It seems to work, but the code is so similar to the file implementing the `uspl` method that it could be improved by creating only one file which would be used to give suggestions from various sources. It could be used as a kind of library, is that the correct term?

### CODE REVIEW

**Comment by lacygoill** [comment]
Sorry, I've just realised that the `'dictionary'` option could contain several filepaths. I don't know how to handle that.

Maybe, instead of:

    let l:suggestions = readfile(&l:dictionary)

One should write:

    let l:suggestions = []
    let l:lists= map(split(&l:dictionary, ','), "readfile(v:val)")
    for list in lists
        let l:suggestions += list
    endfor

**Comment by lacygoill** [comment]
I think this should do it:

```
  let l:suggestions = []
  for l:list in map(split(&l:dictionary, ','), "readfile(v:val)")
      call extend(l:suggestions, l:list)
  endfor

  call filter(l:suggestions, 'stridx(v:val, l:word) == 0')
```

**Comment by lacygoill** [comment]
I added the option `g:mucomplete#dict#match_at_start`, similar to `g:mucomplete#ultisnips#match_at_start`. When it's set to 0, the method should suggest any word from the dictionary containing the word before the cursor, even if it's not at the beginning.

**Comment by lacygoill** [comment]
Well, I'm not sure this is a good idea, after all...

There are several problems to take care of. Like possible commas in the filename, `spell` entry, add the filename of the dictionary in the description field of the menu...

I think I could do that, but I'm not sure you would be interested in it. Let me know what you think.

**Comment by lifepillar** [comment]
I think that this is going towards a direction that is against µcomplete's philosophy. Also, the motivation for this, i.e., overcoming a limitation of some key mappings (https://github.com/lifepillar/vim-mucomplete/issues/43) is not so strong, because the key mappings may be redefined.

Thanks anyway for the effort you've put on it!

**Comment by lifepillar** [comment]
Thinking more about this, a plugin that collects several custom completion methods (abbrev, extended dict, snippets, etc…) might be interesting independent of µcomplete. It could easily provide integration with µcomplete, but also work for other plugins (or without other plugins), and it would allow me to keep µcomplete as minimal as it deserves.

If you decide to take such an endeavour, let me know!

**Pull request closed without merging**
